### ISSUE TITLE
Citation files

### ISSUE THREAD

**Issue by x-tabdeveloping** [tdurieux/anonymous_github#272]
It seems to me that the author's names do not get removed from the `citation.cff` files even when I specify both out first and second names as patterns that should be anonymized.

The file looks like this:
```
cff-version: 0.1.0
message: "When using this package please cite us."
authors:
- family-names: "Kardos"
  given-names: "Márton"
  orcid: "XXXX"
- family-names: "Kostkan"
  given-names: "Jan"
  orcid: "XXXX"
- family-names: "Rocca"
  given-names: "Roberta"
  orcid: "XXXX"
title: "Turftopic: Robust and fast implementations of transformer-based topic models in Python."
version: 0.2.13
date-released: 2024-03-22
url: "XXXX"
```
